#!/usr/bin/env python3

import sys

def main():
    if len(sys.argv) != 2:
        print(f"USAGE: {sys.argv[0]} <file>")
        exit(1)

    file_path = sys.argv[1]

    with open(file_path, 'r', errors='ignore') as file:
        lines = [line.strip() for line in file]

    for line in lines:
        print(line.lower())

if __name__ == "__main__":
    main()

